export const CREATE_EXPENSE_REQUEST = "CREATE_EXPENSE_REQUEST";
export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_RESET = "CREATE_EXPENSE_RESET";
export const CREATE_EXPENSE_ERROR = "CREATE_EXPENSE_ERROR";
export const CREATE_EXPENSE_CLEAR_ERROR = "CREATE_EXPENSE_CLEAR_ERROR";

export const GET_EXPENSE_REQUEST = "CREATE_EXPENSE_REQUEST";
export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS";
export const GET_EXPENSE_RESET = "GET_EXPENSE_RESET";
export const GET_EXPENSE_ERROR = "GET_EXPENSE_ERROR";
export const GET_EXPENSE_CLEAR_ERROR = "GET_EXPENSE_CLEAR_ERROR";
